ALTER TABLE FUNCIONARIO
ADD salario DOUBLE;

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT ck_salario
CHECK (salario>= (SELECT min_salario FROM FUNCAO WHERE FUNCAO.ID = FUNCIONARIO.id_funcao) AND
salario<= (SELECT max_salario FROM FUNCAO WHERE FUNCAO.ID = FUNCIONARIO.id_funcao)); 

